name: Java CI

on:
  workflow_dispatch:
    inputs:
      ALLURE_JOB_RUN_ID:
        description: "Allure Job Run ID"
        required: false

jobs:
  all-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo "Hello ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}!"
#    - name: Set up JDK 1.8
#      uses: actions/setup-java@v1
#      with:
#        java-version: 1.8
#    - name: Build with Gradle
#      run: ./gradlew test
#    - uses: actions/upload-artifact@v2
#      with:
#        name: all-tests
#        path: build/allure-results
